# Generated by Django 4.0.6 on 2022-09-20 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_schools_star_rating'),
        ('questions', '0001_add_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.CharField(default='未記入', max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.schools'),
        ),
    ]
