# Generated by Django 4.0.6 on 2022-10-20 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0007_commenttoanswer_delete_commentforanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentToAnswer',
            new_name='CommentToBestAnswer',
        ),
    ]
