# Generated by Django 4.0.6 on 2023-05-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyabroadinformation',
            name='top_image',
            field=models.FileField(default='blog/top_image/top_image.png', upload_to='information/', verbose_name='サムネイル画像'),
        ),
    ]
