# Generated by Django 4.0.6 on 2022-09-12 07:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_number_of_viewer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_add_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewOfUniverity',
            new_name='ReviewOfUniversity',
        ),
    ]
