# Generated by Django 4.0.6 on 2022-09-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_add_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewofuniversity',
            name='star',
            field=models.CharField(default='未回答', max_length=50),
        ),
    ]
