# Generated by Django 4.0.6 on 2022-09-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviewofuniversity_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewofuniversity',
            name='star',
            field=models.CharField(default=5, max_length=50),
        ),
    ]
