# Generated by Django 4.0.6 on 2022-09-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviewofuniversity_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewofuniversity',
            name='star',
            field=models.IntegerField(default=5),
        ),
    ]
