# Generated by Django 4.0.6 on 2022-11-30 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversationpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationpartner',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
