# Generated by Django 4.0.6 on 2022-12-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_conversationpartner_conversation_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationpartner',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
