# Generated by Django 4.0.6 on 2022-08-25 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_connection_to_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersCount',
        ),
        migrations.AddField(
            model_name='schools',
            name='major',
            field=models.ManyToManyField(to='accounts.majors'),
        ),
        migrations.AlterField(
            model_name='users',
            name='connection',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
