# Generated by Django 4.0.6 on 2022-08-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_youtube_schools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='picture',
            field=models.FileField(blank=True, upload_to='university/'),
        ),
    ]
