# Generated by Django 4.0.6 on 2022-08-31 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_saved_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='saved_university',
            field=models.ManyToManyField(blank=True, related_name='saved_users', to='accounts.schools'),
        ),
        migrations.AlterField(
            model_name='users',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_users', to='accounts.schools'),
        ),
    ]
