# Generated by Django 4.0.6 on 2022-09-07 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_chanege_default_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='connection',
            field=models.ManyToManyField(blank=True, related_name='connected_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
