# Generated by Django 4.0.6 on 2022-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_schools_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='star_rating',
            field=models.IntegerField(default=3),
        ),
    ]
