# Generated by Django 4.0.6 on 2022-10-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_schools_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contributed_points',
            field=models.IntegerField(default=0),
        ),
    ]
