# Generated by Django 4.0.6 on 2022-10-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_contiributed_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='individual_theme_color',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
