# Generated by Django 4.0.6 on 2022-10-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_users_individual_theme_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='individual_theme_color',
            field=models.CharField(default='#D5E9FF', max_length=10),
        ),
    ]
