# Generated by Django 4.0.6 on 2022-11-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_users_saved_university_saveforuniversity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaveForUniversity',
            new_name='LikeForUniversity',
        ),
    ]
