# Generated by Django 4.0.6 on 2022-11-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_followforuser_followed_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='followforuser',
            table='follow_for_user',
        ),
        migrations.AlterModelTable(
            name='likeforuniversity',
            table='like_for_university',
        ),
    ]
