# Generated by Django 4.0.6 on 2022-09-07 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_add_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewofuniverity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reviewofuniverity',
            name='review',
            field=models.TextField(max_length=300),
        ),
    ]
