version: "3.9"
  
services:
  db:
    container_name: "sqlite3"
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    container_name: "django"
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    depends_on:
      - db