# Generated by Django 4.0.6 on 2022-08-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='national',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schools',
            name='place',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
