# Generated by Django 4.0.6 on 2022-08-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_description_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='youtube_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
