# Generated by Django 4.0.6 on 2022-08-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_correct_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='sub_title',
            field=models.CharField(default='自然豊かな、経済学に強い大学', max_length=100),
        ),
    ]
