# Generated by Django 4.0.6 on 2022-09-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_change_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(default='その他', max_length=50),
        ),
    ]
