# Generated by Django 4.0.6 on 2022-09-06 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_state_in_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='joined_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
