# Generated by Django 4.0.6 on 2022-09-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_joined_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.FileField(blank=True, default='pfp/unknown_user', upload_to='pfp/'),
        ),
    ]
