# Generated by Django 4.0.6 on 2022-11-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_national_schools_is_national'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='homepage',
            new_name='homepage_url',
        ),
    ]
