# Generated by Django 4.0.6 on 2022-11-03 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_homepage_schools_homepage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='saved_university',
        ),
        migrations.CreateModel(
            name='SaveForUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.schools')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
