# Generated by Django 4.0.6 on 2022-09-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions_category_questions_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
