# Generated by Django 4.0.6 on 2022-10-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_commentforanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentforanswer',
            options={'verbose_name_plural': '回答に対する質問'},
        ),
        migrations.AlterModelTable(
            name='commentforanswer',
            table='comment_for_answer',
        ),
    ]
