# Generated by Django 4.0.6 on 2022-11-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='seen',
            new_name='is_seen',
        ),
    ]
