# Generated by Django 4.0.6 on 2022-11-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversationpartner_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationpartner',
            name='have_new_message',
            field=models.BooleanField(default=False),
        ),
    ]
