# Generated by Django 4.0.6 on 2022-12-01 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_conversationpartner_have_new_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationpartner',
            name='conversation_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_partner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversationpartner',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
