# Generated by Django 4.0.6 on 2022-09-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='top_image',
            field=models.FileField(default='blog/top_image/top_image.png', upload_to='blog/top_image/', verbose_name='サムネイル画像'),
        ),
    ]
