# Generated by Django 4.0.6 on 2022-10-24 01:13

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_top_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=mdeditor.fields.MDTextField(help_text='Markdown形式で書いてください。', verbose_name='テキスト'),
        ),
    ]
