# Generated by Django 4.0.6 on 2022-10-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
    ]
