# Generated by Django 4.0.6 on 2022-10-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_user_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
