# Generated by Django 4.0.6 on 2022-10-26 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_blog_is_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeForBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
                ('user', models.ForeignKey(on_delete=models.Model, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ブログいいね',
            },
        ),
    ]
