# Generated by Django 4.0.6 on 2022-10-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_totalnumberofview'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_number_of_view',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TotalNumberOfView',
        ),
    ]
