# Generated by Django 4.0.6 on 2022-11-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_likeforblog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='メタデスクリプション'),
        ),
    ]
