# Generated by Django 4.0.6 on 2022-11-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blog_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(blank=True, max_length=150, verbose_name='メタデスクリプション'),
        ),
    ]
