# Generated by Django 4.0.6 on 2022-12-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_blog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='total_number_of_view',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(default='#', max_length=600, verbose_name='url'),
        ),
        migrations.DeleteModel(
            name='LikeForBlog',
        ),
    ]
