# Generated by Django 4.0.6 on 2022-12-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_remove_blog_content_remove_blog_total_number_of_view_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '投稿', 'verbose_name_plural': '投稿'},
        ),
    ]
