name: Run All Looben Tests
on: [push]
jobs:
  unittest:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Excute tests
        env:
          SECRET_KEY: 2c8a67ed46c7f1d1ed7b4ae604801a79ca2213409372b4bdf8 
          DEBUG: True
        run: docker-compose build && docker-compose run --rm web sh -c "export DJANGO_SETTINGS_MODULE=Looben.settings && pytest"
